
class Constant:
    MAX_INT_SIZE= 10**100
    PYGAME_DISPLAY_MODE_WIDTH=1300
    PYGAME_DISPLAY_MODE_HEIGHT=800
    MAX_SENSOR_DISTANCE=30
    MAX_STEERING_ANGLE=360
    MAX_VEL=3
    TRACK_SCALE_FACTOR=1
    TRACK_BORDER_SCALE_FACTOR=1
    OBSTACLE_SCALE_FACTOR=0.02
    DELIVERY_LOCATION_SCALE_FACTOR=0.05
    CAR_SCALE_FACTOR=0.3
    DELIVERY_VEHICLE_START_POS_X=220
    DELIVERY_VEHICLE_START_POS_Y=370
    SENSORS_COLLISION_DISTANCE=14
    TIMESTEP_PUNISHMENT=0.05

